// <auto-generated />
using System;
using GymTrackerApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymTrackerApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260418160812_SeedCorrectExerciseImages")]
    partial class SeedCorrectExerciseImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymTrackerApp.Data.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("MuscleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("MuscleId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "The king of leg exercises. Targets quads, hamstrings, and glutes.",
                            ImageUrl = "https://thumbs.dreamstime.com/b/basic-rgb-228479863.jpg",
                            MuscleId = 13,
                            Name = "Squat"
                        },
                        new
                        {
                            Id = 2,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "A compound movement that works the entire posterior chain.",
                            ImageUrl = "https://static.vecteezy.com/system/resources/previews/006/417/718/non_2x/man-doing-barbell-deadlifts-exercise-flat-illustration-isolated-on-white-background-free-vector.jpg",
                            MuscleId = 3,
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = 4,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "A classic shoulder builder performed with a barbell.",
                            ImageUrl = "https://www.shutterstock.com/image-vector/man-doing-overhead-dumbbell-shoulder-600nw-2031950852.jpg",
                            MuscleId = 6,
                            Name = "Overhead Press"
                        },
                        new
                        {
                            Id = 5,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "A machine exercise that targets the latissimus dorsi.",
                            ImageUrl = "https://thumbs.dreamstime.com/b/basic-rgb-248990552.jpg",
                            MuscleId = 4,
                            Name = "Lat Pulldown"
                        },
                        new
                        {
                            Id = 6,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "An isolation exercise for the biceps.",
                            ImageUrl = "https://thumbs.dreamstime.com/b/man-doing-barbell-curls-exercise-standing-bicep-curl-arm-workout-man-doing-barbell-curls-exercise-standing-bicep-curl-arm-workout-201313766.jpg",
                            MuscleId = 7,
                            Name = "Barbell Curl"
                        },
                        new
                        {
                            Id = 7,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "An isolation exercise for the triceps using a cable machine.",
                            ImageUrl = "https://www.shutterstock.com/image-vector/man-doing-cable-rope-pushdown-260nw-2169476315.jpg",
                            MuscleId = 8,
                            Name = "Tricep Rope Pushdown"
                        },
                        new
                        {
                            Id = 8,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "Isolation exercise for the hamstrings.",
                            ImageUrl = "https://t4.ftcdn.net/jpg/04/66/42/97/360_F_466429708_7KoDFAbfozTD5YcOneKgX5K6MaUqtEqF.jpg",
                            MuscleId = 14,
                            Name = "Leg Curl"
                        },
                        new
                        {
                            Id = 9,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "Simple but effective exercise for building calves.",
                            ImageUrl = "https://thumbs.dreamstime.com/b/man-doing-standing-calf-raise-assisted-machine-man-doing-standing-calf-raise-assisted-machine-flat-vector-illustration-259075988.jpg",
                            MuscleId = 16,
                            Name = "Calf Raise"
                        },
                        new
                        {
                            Id = 10,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "The ultimate chest builder. A compound push exercise using a barbell.",
                            ImageUrl = "https://www.shutterstock.com/shutterstock/photos/1841766727/display_1500/stock-vector-man-doing-barbell-bench-press-chest-press-flat-vector-illustration-isolated-on-white-background-1841766727.jpg",
                            MuscleId = 1,
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = 11,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "A bodyweight exercise that builds upper back and lat width.",
                            ImageUrl = "https://thumbs.dreamstime.com/b/man-doing-pull-ups-exercise-flat-vector-illustration-man-doing-pull-ups-exercise-flat-vector-illustration-isolated-white-228445780.jpg",
                            MuscleId = 2,
                            Name = "Pull-up"
                        },
                        new
                        {
                            Id = 12,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "A classic bodyweight exercise for chest, shoulders, and triceps.",
                            ImageUrl = "https://thumbs.dreamstime.com/b/art-illustration-200146808.jpg",
                            MuscleId = 1,
                            Name = "Push-up"
                        },
                        new
                        {
                            Id = 13,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "An isolation exercise to build the upper trapezius muscles.",
                            ImageUrl = "https://www.shutterstock.com/image-vector/man-doing-dumbbell-shrugs-exercise-260nw-1986762905.jpg",
                            MuscleId = 5,
                            Name = "Dumbbell Shrugs"
                        },
                        new
                        {
                            Id = 14,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "An isolation exercise for forearm size and grip strength.",
                            ImageUrl = "https://thumbs.dreamstime.com/b/man-doing-seated-palm-wrist-curls-exercise-flat-vector-illustration-isolated-white-background-223602922.jpg",
                            MuscleId = 9,
                            Name = "Wrist Curls"
                        },
                        new
                        {
                            Id = 15,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "A basic core exercise targeting the upper abdominal muscles.",
                            ImageUrl = "https://www.shutterstock.com/image-vector/man-doing-crunches-abdominals-exercise-600nw-1842272014.jpg",
                            MuscleId = 10,
                            Name = "Crunches"
                        },
                        new
                        {
                            Id = 16,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "An advanced core exercise primarily targeting the lower abs.",
                            ImageUrl = "https://thumbs.dreamstime.com/b/art-illustration-201075897.jpg",
                            MuscleId = 11,
                            Name = "Hanging Leg Raises"
                        },
                        new
                        {
                            Id = 17,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "A core exercise designed to target the oblique muscles.",
                            ImageUrl = "https://previews.123rf.com/images/lioputra/lioputra2111/lioputra211100044/177362267-man-doing-weighted-russian-mason-twists-exercise-flat-vector-illustration-isolated-on-white.jpg",
                            MuscleId = 12,
                            Name = "Russian Twists"
                        },
                        new
                        {
                            Id = 18,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "The best exercise for isolating and building the glutes.",
                            ImageUrl = "https://thumbs.dreamstime.com/b/basic-rgb-221835143.jpg",
                            MuscleId = 15,
                            Name = "Hip Thrusts"
                        },
                        new
                        {
                            Id = 19,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "A machine isolation exercise specifically for the quadriceps.",
                            ImageUrl = "https://www.shutterstock.com/image-vector/man-doing-seated-machine-leg-260nw-2316630653.jpg",
                            MuscleId = 13,
                            Name = "Leg Extension"
                        },
                        new
                        {
                            Id = 20,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "Excellent for targeting the upper portion of the pectoral muscles.",
                            ImageUrl = "https://static.vecteezy.com/system/resources/previews/032/647/051/non_2x/man-doing-incline-dumbbell-bench-press-twist-exercise-vector.jpg",
                            MuscleId = 1,
                            Name = "Incline Dumbbell Press"
                        },
                        new
                        {
                            Id = 21,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "An isolation exercise that provides constant tension on the chest.",
                            ImageUrl = "https://www.shutterstock.com/image-vector/man-doing-standing-cable-crossover-600nw-2164371137.jpg",
                            MuscleId = 1,
                            Name = "Cable Crossover"
                        },
                        new
                        {
                            Id = 22,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "Builds middle back thickness and improves posture.",
                            ImageUrl = "https://www.shutterstock.com/image-vector/man-doing-seated-low-cable-600nw-2205405029.jpg",
                            MuscleId = 2,
                            Name = "Seated Cable Row"
                        },
                        new
                        {
                            Id = 23,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "A heavy compound pulling exercise for mass in the lats and mid-back.",
                            ImageUrl = "https://www.shutterstock.com/image-vector/man-doing-bent-over-t-260nw-1837676119.jpg",
                            MuscleId = 4,
                            Name = "T-Bar Row"
                        },
                        new
                        {
                            Id = 24,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "The best exercise for isolating the side deltoids to build wider shoulders.",
                            ImageUrl = "https://www.shutterstock.com/shutterstock/photos/2044846490/display_1500/stock-vector-man-doing-seated-dumbbell-lateral-raises-power-partials-exercise-flat-vector-illustration-2044846490.jpg",
                            MuscleId = 6,
                            Name = "Lateral Raise"
                        },
                        new
                        {
                            Id = 25,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "Crucial for rear deltoid development and overall shoulder health.",
                            ImageUrl = "https://www.shutterstock.com/image-vector/man-doing-cable-face-pull-600w-1885368556.jpg",
                            MuscleId = 6,
                            Name = "Face Pulls"
                        },
                        new
                        {
                            Id = 26,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "Targets the brachialis and the brachioradialis for thicker arms.",
                            ImageUrl = "https://static.vecteezy.com/system/resources/previews/008/572/891/non_2x/man-doing-standing-dumbbell-bicep-hammer-curls-flat-illustration-isolated-on-different-layer-workout-character-vector.jpg",
                            MuscleId = 7,
                            Name = "Hammer Curl"
                        },
                        new
                        {
                            Id = 27,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "Strict isolation for the biceps, preventing momentum.",
                            ImageUrl = "https://static.vecteezy.com/system/resources/previews/017/423/220/non_2x/man-doing-one-arm-dumbbell-preacher-curl-side-view-flat-illustration-isolated-on-different-layer-workout-character-vector.jpg",
                            MuscleId = 7,
                            Name = "Preacher Curl"
                        },
                        new
                        {
                            Id = 28,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "A barbell extension movement that heavily targets the long head of the triceps.",
                            ImageUrl = "https://www.gofitnessplan.com/images/exercises/mixed/dumbbell-triceps-skullcrusher.jpg",
                            MuscleId = 8,
                            Name = "Skull Crushers"
                        },
                        new
                        {
                            Id = 29,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "A heavy compound bodyweight movement for thick triceps and chest.",
                            ImageUrl = "https://www.shutterstock.com/image-vector/chair-tricep-dips-exercise-guide-600nw-2658932277.jpg",
                            MuscleId = 8,
                            Name = "Tricep Dips"
                        },
                        new
                        {
                            Id = 30,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "A unilateral leg exercise that builds immense quad and glute strength.",
                            ImageUrl = "https://thumbs.dreamstime.com/b/man-doing-bulgarian-split-squats-exercise-flat-vector-illustration-isolated-white-background-man-doing-bulgarian-split-squats-224056268.jpg",
                            MuscleId = 13,
                            Name = "Bulgarian Split Squat"
                        },
                        new
                        {
                            Id = 31,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "A machine variation of the squat that isolates the quads effectively.",
                            ImageUrl = "https://static.vecteezy.com/system/resources/thumbnails/008/418/359/small/man-doing-hack-squat-exercise-flat-illustration-isolated-on-white-background-vector.jpg",
                            MuscleId = 13,
                            Name = "Hack Squat"
                        },
                        new
                        {
                            Id = 32,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "Focuses entirely on the hamstrings and glutes through a hip hinge.",
                            ImageUrl = "https://www.shutterstock.com/image-vector/woman-doing-romanian-deadlift-exercise-600nw-2118315965.jpg",
                            MuscleId = 14,
                            Name = "Romanian Deadlift (RDL)"
                        },
                        new
                        {
                            Id = 33,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "Builds immense lower back, glute, and hamstring strength.",
                            ImageUrl = "https://thumbs.dreamstime.com/z/basic-rgb-252099603.jpg",
                            MuscleId = 3,
                            Name = "Good Mornings"
                        },
                        new
                        {
                            Id = 34,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "Targets the soleus muscle of the calves.",
                            ImageUrl = "https://www.shutterstock.com/image-vector/man-doing-seated-dumbbell-chair-600nw-2214158705.jpg",
                            MuscleId = 16,
                            Name = "Seated Calf Raise"
                        },
                        new
                        {
                            Id = 35,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "A full-body carry that builds extreme grip strength and traps.",
                            ImageUrl = "https://www.shutterstock.com/image-vector/man-doing-single-one-arm-260nw-2389002669.jpg",
                            MuscleId = 9,
                            Name = "Farmer's Walk"
                        },
                        new
                        {
                            Id = 36,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "An isometric core exercise that builds endurance and stability.",
                            ImageUrl = "https://static.vecteezy.com/system/resources/thumbnails/008/573/039/small/man-doing-plank-abdominals-exercise-flat-illustration-isolated-on-white-background-vector.jpg",
                            MuscleId = 10,
                            Name = "Plank"
                        },
                        new
                        {
                            Id = 37,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "Dynamic movement hitting both the rectus abdominis and obliques.",
                            ImageUrl = "https://www.shutterstock.com/image-vector/man-doing-abdominal-workout-bicycle-600nw-1831638793.jpg",
                            MuscleId = 12,
                            Name = "Bicycle Crunches"
                        },
                        new
                        {
                            Id = 38,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "Rotational core movement perfect for athletic performance and obliques.",
                            ImageUrl = "https://static.vecteezy.com/system/resources/previews/006/417/746/non_2x/man-character-doing-downward-cable-wood-chops-exercise-flat-illustration-isolated-on-different-layers-free-vector.jpg",
                            MuscleId = 12,
                            Name = "Cable Woodchoppers"
                        });
                });

            modelBuilder.Entity("GymTrackerApp.Data.Models.Muscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Muscles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The pectoralis major makes up the bulk of the chest muscles. It is responsible for movement of the shoulder joint and arms across the body.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Chest",
                            Name = "Chest"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Includes the rhomboids and upper latissimus dorsi. These muscles pull the shoulder blades together and help maintain proper posture.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Upper+Back",
                            Name = "Upper Back"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The erector spinae muscles support the spine and allow for extending the back. Crucial for core stability and lifting.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Lower+Back",
                            Name = "Lower Back"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The latissimus dorsi is the largest muscle in the upper body, responsible for pulling actions and giving the back its V-taper.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Lats",
                            Name = "Lats"
                        },
                        new
                        {
                            Id = 5,
                            Description = "The trapezius muscles run down the neck and middle back. They elevate and depress the shoulder blades.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Traps",
                            Name = "Traps"
                        },
                        new
                        {
                            Id = 6,
                            Description = "The deltoids consist of three heads (anterior, lateral, and posterior) that allow the arms to lift and rotate in all directions.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Shoulders",
                            Name = "Shoulders"
                        },
                        new
                        {
                            Id = 7,
                            Description = "The biceps brachii sits on the front of the upper arm and is responsible for elbow flexion (curling) and forearm rotation.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Biceps",
                            Name = "Biceps"
                        },
                        new
                        {
                            Id = 8,
                            Description = "The triceps brachii makes up about 2/3 of the upper arm's mass. It consists of three heads responsible for extending the elbow.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Triceps",
                            Name = "Triceps"
                        },
                        new
                        {
                            Id = 9,
                            Description = "A complex group of smaller muscles responsible for grip strength, wrist flexion, and extension.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Forearms",
                            Name = "Forearms"
                        },
                        new
                        {
                            Id = 10,
                            Description = "The rectus abdominis is the front core muscle layer. It flexes the spine and provides essential core stabilization.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Abs",
                            Name = "Abs"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Situated on the sides of the abdomen, these muscles handle rotational movements and lateral flexion of the torso.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Obliques",
                            Name = "Obliques"
                        },
                        new
                        {
                            Id = 12,
                            Description = "The gluteus maximus is one of the strongest muscles in the human body, serving as the main extensor of the hip.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Glutes",
                            Name = "Glutes"
                        },
                        new
                        {
                            Id = 13,
                            Description = "The quadriceps femoris consists of four large muscles on the front of the thigh that extend the knee.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Quads",
                            Name = "Quads"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Located on the back of the thigh, these muscles are responsible for knee flexion and assist in hip extension.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Hamstrings",
                            Name = "Hamstrings"
                        },
                        new
                        {
                            Id = 15,
                            Description = "The inner thigh muscles that pull the legs together toward the midline of the body.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Adductors",
                            Name = "Adductors"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Consisting of the gastrocnemius and soleus, these lower leg muscles act to flex the foot and ankle.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Calves",
                            Name = "Calves"
                        });
                });

            modelBuilder.Entity("GymTrackerApp.Data.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "A comprehensive workout targeting all major muscle groups.",
                            Title = "Full Body Workout"
                        },
                        new
                        {
                            Id = 2,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "Focuses on building strength in the upper body.",
                            Title = "Upper Body"
                        },
                        new
                        {
                            Id = 3,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "Targets the lower body muscles for strength and endurance.",
                            Title = "Lower Body"
                        },
                        new
                        {
                            Id = 4,
                            CreatorId = "22222222-3333-4444-5555-666666666666",
                            Description = "A comprehensive workout targeting all major muscle groups in the body.",
                            Title = "Full Body"
                        },
                        new
                        {
                            Id = 5,
                            CreatorId = "22222222-3333-4444-5555-666666666666",
                            Description = "Focuses on building strength in the pushing muscles.",
                            Title = "Push"
                        },
                        new
                        {
                            Id = 6,
                            CreatorId = "22222222-3333-4444-5555-666666666666",
                            Description = "Targets the pulling muscles for strength and endurance.",
                            Title = "Pull"
                        },
                        new
                        {
                            Id = 7,
                            CreatorId = "22222222-3333-4444-5555-666666666666",
                            Description = "Focuses on building strength in the leg muscles.",
                            Title = "Legs"
                        });
                });

            modelBuilder.Entity("GymTrackerApp.Data.Models.WorkoutExercise", b =>
                {
                    b.Property<int>("WorkoutId")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("WorkoutId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("WorkoutExercises");

                    b.HasData(
                        new
                        {
                            WorkoutId = 1,
                            ExerciseId = 1,
                            Reps = 6,
                            Sets = 4,
                            Weight = 100.0
                        },
                        new
                        {
                            WorkoutId = 1,
                            ExerciseId = 10,
                            Reps = 8,
                            Sets = 4,
                            Weight = 80.0
                        },
                        new
                        {
                            WorkoutId = 1,
                            ExerciseId = 11,
                            Reps = 8,
                            Sets = 4,
                            Weight = 0.0
                        },
                        new
                        {
                            WorkoutId = 1,
                            ExerciseId = 4,
                            Reps = 10,
                            Sets = 3,
                            Weight = 50.0
                        },
                        new
                        {
                            WorkoutId = 2,
                            ExerciseId = 20,
                            Reps = 8,
                            Sets = 4,
                            Weight = 60.0
                        },
                        new
                        {
                            WorkoutId = 2,
                            ExerciseId = 23,
                            Reps = 8,
                            Sets = 4,
                            Weight = 70.0
                        },
                        new
                        {
                            WorkoutId = 2,
                            ExerciseId = 24,
                            Reps = 12,
                            Sets = 3,
                            Weight = 15.0
                        },
                        new
                        {
                            WorkoutId = 2,
                            ExerciseId = 28,
                            Reps = 10,
                            Sets = 3,
                            Weight = 35.0
                        },
                        new
                        {
                            WorkoutId = 3,
                            ExerciseId = 2,
                            Reps = 5,
                            Sets = 4,
                            Weight = 120.0
                        },
                        new
                        {
                            WorkoutId = 3,
                            ExerciseId = 30,
                            Reps = 10,
                            Sets = 3,
                            Weight = 40.0
                        },
                        new
                        {
                            WorkoutId = 3,
                            ExerciseId = 19,
                            Reps = 12,
                            Sets = 3,
                            Weight = 50.0
                        },
                        new
                        {
                            WorkoutId = 4,
                            ExerciseId = 2,
                            Reps = 5,
                            Sets = 4,
                            Weight = 110.0
                        },
                        new
                        {
                            WorkoutId = 4,
                            ExerciseId = 12,
                            Reps = 15,
                            Sets = 4,
                            Weight = 0.0
                        },
                        new
                        {
                            WorkoutId = 4,
                            ExerciseId = 5,
                            Reps = 10,
                            Sets = 4,
                            Weight = 55.0
                        },
                        new
                        {
                            WorkoutId = 5,
                            ExerciseId = 10,
                            Reps = 8,
                            Sets = 4,
                            Weight = 75.0
                        },
                        new
                        {
                            WorkoutId = 5,
                            ExerciseId = 4,
                            Reps = 8,
                            Sets = 4,
                            Weight = 45.0
                        },
                        new
                        {
                            WorkoutId = 5,
                            ExerciseId = 29,
                            Reps = 12,
                            Sets = 3,
                            Weight = 0.0
                        },
                        new
                        {
                            WorkoutId = 5,
                            ExerciseId = 21,
                            Reps = 12,
                            Sets = 3,
                            Weight = 25.0
                        },
                        new
                        {
                            WorkoutId = 6,
                            ExerciseId = 11,
                            Reps = 8,
                            Sets = 4,
                            Weight = 0.0
                        },
                        new
                        {
                            WorkoutId = 6,
                            ExerciseId = 22,
                            Reps = 10,
                            Sets = 4,
                            Weight = 60.0
                        },
                        new
                        {
                            WorkoutId = 6,
                            ExerciseId = 6,
                            Reps = 10,
                            Sets = 3,
                            Weight = 30.0
                        },
                        new
                        {
                            WorkoutId = 6,
                            ExerciseId = 25,
                            Reps = 15,
                            Sets = 3,
                            Weight = 20.0
                        },
                        new
                        {
                            WorkoutId = 7,
                            ExerciseId = 1,
                            Reps = 6,
                            Sets = 4,
                            Weight = 95.0
                        },
                        new
                        {
                            WorkoutId = 7,
                            ExerciseId = 32,
                            Reps = 8,
                            Sets = 4,
                            Weight = 80.0
                        },
                        new
                        {
                            WorkoutId = 7,
                            ExerciseId = 8,
                            Reps = 12,
                            Sets = 3,
                            Weight = 40.0
                        },
                        new
                        {
                            WorkoutId = 7,
                            ExerciseId = 9,
                            Reps = 15,
                            Sets = 4,
                            Weight = 60.0
                        });
                });

            modelBuilder.Entity("GymTrackerApp.Data.Models.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "admin-role",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "user-role",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-2222-3333-4444-555555555555",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "admin-concurrency-stamp-1234",
                            Email = "admin@gymtracker.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GYMTRACKER.COM",
                            NormalizedUserName = "ADMIN@GYMTRACKER.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPLDGkgokSex9Yy1N5AotosXTKzXUPHYrSNKcQcDYfceG9Ij9w8333qqlMv4UWKvcQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "admin-security-stamp-1234",
                            TwoFactorEnabled = false,
                            UserName = "admin@gymtracker.com"
                        },
                        new
                        {
                            Id = "22222222-3333-4444-5555-666666666666",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "testuser-concurrency-stamp-1234",
                            Email = "testuser123@gymtracker.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TESTUSER123@GYMTRACKER.COM",
                            NormalizedUserName = "TESTUSER123",
                            PasswordHash = "AQAAAAIAAYagAAAAEPLDGkgokSex9Yy1N5AotosXTKzXUPHYrSNKcQcDYfceG9Ij9w8333qqlMv4UWKvcQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "testuser-security-stamp-1234",
                            TwoFactorEnabled = false,
                            UserName = "TestUser123"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "11111111-2222-3333-4444-555555555555",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "22222222-3333-4444-5555-666666666666",
                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GymTrackerApp.Data.Models.Exercise", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTrackerApp.Data.Models.Muscle", "Muscle")
                        .WithMany("Exercises")
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("GymTrackerApp.Data.Models.Workout", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("GymTrackerApp.Data.Models.WorkoutExercise", b =>
                {
                    b.HasOne("GymTrackerApp.Data.Models.Exercise", "Exercise")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymTrackerApp.Data.Models.Workout", "Workout")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("GymTrackerApp.Data.Models.WorkoutSession", b =>
                {
                    b.HasOne("GymTrackerApp.Data.Models.Workout", "Workout")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymTrackerApp.Data.Models.Exercise", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("GymTrackerApp.Data.Models.Muscle", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("GymTrackerApp.Data.Models.Workout", b =>
                {
                    b.Navigation("WorkoutExercises");

                    b.Navigation("WorkoutSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
