// <auto-generated />
using System;
using GymTrackerApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymTrackerApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260403093603_SeedAdmin")]
    partial class SeedAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymTrackerApp.Data.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("MuscleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("MuscleId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "The king of leg exercises. Targets quads, hamstrings, and glutes.",
                            ImageUrl = "https://example.com/squat.jpg",
                            MuscleId = 13,
                            Name = "Squat"
                        },
                        new
                        {
                            Id = 2,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "A compound movement that works the entire posterior chain.",
                            ImageUrl = "https://example.com/deadlift.jpg",
                            MuscleId = 3,
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = 4,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "A classic shoulder builder performed with a barbell.",
                            ImageUrl = "https://example.com/ohp.jpg",
                            MuscleId = 6,
                            Name = "Overhead Press"
                        },
                        new
                        {
                            Id = 5,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "A machine exercise that targets the latissimus dorsi.",
                            ImageUrl = "https://example.com/latpulldown.jpg",
                            MuscleId = 4,
                            Name = "Lat Pulldown"
                        },
                        new
                        {
                            Id = 6,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "An isolation exercise for the biceps.",
                            ImageUrl = "https://example.com/bicepcurl.jpg",
                            MuscleId = 7,
                            Name = "Barbell Curl"
                        },
                        new
                        {
                            Id = 7,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "An isolation exercise for the triceps using a cable machine.",
                            ImageUrl = "https://example.com/triceppushdown.jpg",
                            MuscleId = 8,
                            Name = "Tricep Rope Pushdown"
                        },
                        new
                        {
                            Id = 8,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "Isolation exercise for the hamstrings.",
                            ImageUrl = "https://example.com/legcurl.jpg",
                            MuscleId = 14,
                            Name = "Leg Curl"
                        },
                        new
                        {
                            Id = 9,
                            CreatorId = "11111111-2222-3333-4444-555555555555",
                            Description = "Simple but effective exercise for building calves.",
                            ImageUrl = "https://example.com/calfraise.jpg",
                            MuscleId = 16,
                            Name = "Calf Raise"
                        });
                });

            modelBuilder.Entity("GymTrackerApp.Data.Models.Muscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Muscles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The pectoralis major makes up the bulk of the chest muscles. It is responsible for movement of the shoulder joint and arms across the body.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Chest",
                            Name = "Chest"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Includes the rhomboids and upper latissimus dorsi. These muscles pull the shoulder blades together and help maintain proper posture.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Upper+Back",
                            Name = "Upper Back"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The erector spinae muscles support the spine and allow for extending the back. Crucial for core stability and lifting.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Lower+Back",
                            Name = "Lower Back"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The latissimus dorsi is the largest muscle in the upper body, responsible for pulling actions and giving the back its V-taper.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Lats",
                            Name = "Lats"
                        },
                        new
                        {
                            Id = 5,
                            Description = "The trapezius muscles run down the neck and middle back. They elevate and depress the shoulder blades.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Traps",
                            Name = "Traps"
                        },
                        new
                        {
                            Id = 6,
                            Description = "The deltoids consist of three heads (anterior, lateral, and posterior) that allow the arms to lift and rotate in all directions.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Shoulders",
                            Name = "Shoulders"
                        },
                        new
                        {
                            Id = 7,
                            Description = "The biceps brachii sits on the front of the upper arm and is responsible for elbow flexion (curling) and forearm rotation.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Biceps",
                            Name = "Biceps"
                        },
                        new
                        {
                            Id = 8,
                            Description = "The triceps brachii makes up about 2/3 of the upper arm's mass. It consists of three heads responsible for extending the elbow.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Triceps",
                            Name = "Triceps"
                        },
                        new
                        {
                            Id = 9,
                            Description = "A complex group of smaller muscles responsible for grip strength, wrist flexion, and extension.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Forearms",
                            Name = "Forearms"
                        },
                        new
                        {
                            Id = 10,
                            Description = "The rectus abdominis is the front core muscle layer. It flexes the spine and provides essential core stabilization.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Abs",
                            Name = "Abs"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Situated on the sides of the abdomen, these muscles handle rotational movements and lateral flexion of the torso.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Obliques",
                            Name = "Obliques"
                        },
                        new
                        {
                            Id = 12,
                            Description = "The gluteus maximus is one of the strongest muscles in the human body, serving as the main extensor of the hip.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Glutes",
                            Name = "Glutes"
                        },
                        new
                        {
                            Id = 13,
                            Description = "The quadriceps femoris consists of four large muscles on the front of the thigh that extend the knee.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Quads",
                            Name = "Quads"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Located on the back of the thigh, these muscles are responsible for knee flexion and assist in hip extension.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Hamstrings",
                            Name = "Hamstrings"
                        },
                        new
                        {
                            Id = 15,
                            Description = "The inner thigh muscles that pull the legs together toward the midline of the body.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Adductors",
                            Name = "Adductors"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Consisting of the gastrocnemius and soleus, these lower leg muscles act to flex the foot and ankle.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Calves",
                            Name = "Calves"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Various muscles supporting the cervical spine, responsible for rotating and bending the head.",
                            ImageUrl = "https://placehold.co/600x400/212529/0dcaf0?text=Neck",
                            Name = "Neck"
                        });
                });

            modelBuilder.Entity("GymTrackerApp.Data.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("GymTrackerApp.Data.Models.WorkoutExercise", b =>
                {
                    b.Property<int>("WorkoutId")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("WorkoutId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("WorkoutExercises");
                });

            modelBuilder.Entity("GymTrackerApp.Data.Models.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "admin-role",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "user-role",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-2222-3333-4444-555555555555",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "admin-concurrency-stamp-1234",
                            Email = "admin@gymtracker.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GYMTRACKER.COM",
                            NormalizedUserName = "ADMIN@GYMTRACKER.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPLDGkgokSex9Yy1N5AotosXTKzXUPHYrSNKcQcDYfceG9Ij9w8333qqlMv4UWKvcQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "admin-security-stamp-1234",
                            TwoFactorEnabled = false,
                            UserName = "admin@gymtracker.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "11111111-2222-3333-4444-555555555555",
                            RoleId = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GymTrackerApp.Data.Models.Exercise", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTrackerApp.Data.Models.Muscle", "Muscle")
                        .WithMany("Exercises")
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("GymTrackerApp.Data.Models.Workout", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("GymTrackerApp.Data.Models.WorkoutExercise", b =>
                {
                    b.HasOne("GymTrackerApp.Data.Models.Exercise", "Exercise")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymTrackerApp.Data.Models.Workout", "Workout")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("GymTrackerApp.Data.Models.WorkoutSession", b =>
                {
                    b.HasOne("GymTrackerApp.Data.Models.Workout", "Workout")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymTrackerApp.Data.Models.Exercise", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("GymTrackerApp.Data.Models.Muscle", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("GymTrackerApp.Data.Models.Workout", b =>
                {
                    b.Navigation("WorkoutExercises");

                    b.Navigation("WorkoutSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
